import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';

export default defineConfig({
    plugins: [
        laravel({
            input: [
                'public/css/prettify.css',
                'public/css/jquery-jvectormap-1.2.2.css',
                'public/css/dataTables.bootstrap4.min.css',
                'public/css/responsive.bootstrap4.min.css',
                'public/css/autoFill.bootstrap4.min.css',
                'public/css/keyTable.bootstrap4.min.css',
                'public/css/bootstrap.min.css',
                'public/css/icons.min.css',
                'public/css/admin-app.min.css',
                'resources/css/app.css',

                'public/js/bootstrap.bundle.min.js',
                'public/js/metisMenu.min.js',
                'public/js/simplebar.min.js',
                'public/js/waves.min.js',
                'public/js/table-edits.min.js',
                'public/js/prettify.js',
                'public/js/apexcharts.min.js',
                'public/js/jquery-jvectormap-1.2.2.min.js',
                'public/js/jquery-jvectormap-us-merc-en.js',
                'public/js/jquery.dataTables.min.js',
                'public/js/dataTables.bootstrap4.min.js',
                'public/js/responsive.bootstrap4.min.js',
                'public/js/dataTables.buttons.min.js',
                'public/js/buttons.bootstrap4.min.js',
                'public/js/jszip.min.js',
                'public/js/pdfmake.min.js',
                'public/js/vfs_fonts.js',
                'public/js/buttons.html5.min.js',
                'public/js/buttons.print.min.js',
                'public/js/buttons.colVis.min.js',
                'public/js/dataTables.keyTable.min.js',
                'public/js/dataTables.select.min.js',
                'public/js/dataTables.responsive.min.js',
                'public/js/jquery.bootstrap.wizard.min.js',
                'public/pages/js/dashboard.init.js',
                'public/pages/js/table-editable.init.js',
                'public/pages/js/datatables.init.js',
                'public/pages/js/form-wizard.init.js',
                'public/js/admin-app.js',
                'resources/js/app.js',
            ],
            refresh: true,
        }),
    ],
});
